# Generated by Django 5.0.1 on 2024-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_cakevarient_basket_object_basketitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakevarient',
            name='images',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='product_images'),
        ),
    ]
