# Generated by Django 5.0.1 on 2024-03-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_cakevarient_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakevarient',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
