# Generated by Django 5.0.1 on 2024-03-10 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_cakevarient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
