# Generated by Django 5.0.1 on 2024-03-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_weight_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakevarient',
            name='weight_object',
        ),
        migrations.AddField(
            model_name='cakevarient',
            name='weight_object',
            field=models.ManyToManyField(to='store.weight'),
        ),
    ]
