# Generated by Django 5.0.1 on 2024-03-12 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_cakevarient_weight_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cakevarient',
            name='qty',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
