# Generated by Django 5.0.1 on 2024-03-13 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cakevarient_occassion_object'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cakevarient',
            name='occassion_object',
        ),
    ]
