# Generated by Django 5.0.1 on 2024-03-13 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_cakevarient_occassion_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='weight_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.weight'),
        ),
    ]
