# Generated by Django 5.0.1 on 2024-03-14 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_basketitem_is_order_placed'),
    ]

    operations = [
        migrations.AddField(
            model_name='basketitem',
            name='occassion_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.occassion'),
        ),
    ]
