# Generated by Django 5.0.1 on 2024-03-28 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_tags_cakevarient_tag_objects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
